/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProyectosRouteImport } from './routes/_authenticated/proyectos'
import { Route as AuthenticatedGastosGeneralesRouteImport } from './routes/_authenticated/gastos-generales'
import { Route as AuthenticatedGastosRouteImport } from './routes/_authenticated/gastos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedCobrosRouteImport } from './routes/_authenticated/cobros'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedProyectosIdRouteImport } from './routes/_authenticated/proyectos.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProyectosRoute = AuthenticatedProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGastosGeneralesRoute =
  AuthenticatedGastosGeneralesRouteImport.update({
    id: '/gastos-generales',
    path: '/gastos-generales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGastosRoute = AuthenticatedGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCobrosRoute = AuthenticatedCobrosRouteImport.update({
  id: '/cobros',
  path: '/cobros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProyectosIdRoute =
  AuthenticatedProyectosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProyectosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobros': typeof AuthenticatedCobrosRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/gastos-generales': typeof AuthenticatedGastosGeneralesRoute
  '/proyectos': typeof AuthenticatedProyectosRouteWithChildren
  '/proyectos/$id': typeof AuthenticatedProyectosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cobros': typeof AuthenticatedCobrosRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/gastos-generales': typeof AuthenticatedGastosGeneralesRoute
  '/proyectos': typeof AuthenticatedProyectosRouteWithChildren
  '/proyectos/$id': typeof AuthenticatedProyectosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/cobros': typeof AuthenticatedCobrosRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gastos': typeof AuthenticatedGastosRoute
  '/_authenticated/gastos-generales': typeof AuthenticatedGastosGeneralesRoute
  '/_authenticated/proyectos': typeof AuthenticatedProyectosRouteWithChildren
  '/_authenticated/proyectos/$id': typeof AuthenticatedProyectosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/cobros'
    | '/configuracion'
    | '/dashboard'
    | '/gastos'
    | '/gastos-generales'
    | '/proyectos'
    | '/proyectos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/cobros'
    | '/configuracion'
    | '/dashboard'
    | '/gastos'
    | '/gastos-generales'
    | '/proyectos'
    | '/proyectos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/cobros'
    | '/_authenticated/configuracion'
    | '/_authenticated/dashboard'
    | '/_authenticated/gastos'
    | '/_authenticated/gastos-generales'
    | '/_authenticated/proyectos'
    | '/_authenticated/proyectos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/proyectos': {
      id: '/_authenticated/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof AuthenticatedProyectosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gastos-generales': {
      id: '/_authenticated/gastos-generales'
      path: '/gastos-generales'
      fullPath: '/gastos-generales'
      preLoaderRoute: typeof AuthenticatedGastosGeneralesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gastos': {
      id: '/_authenticated/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AuthenticatedGastosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobros': {
      id: '/_authenticated/cobros'
      path: '/cobros'
      fullPath: '/cobros'
      preLoaderRoute: typeof AuthenticatedCobrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proyectos/$id': {
      id: '/_authenticated/proyectos/$id'
      path: '/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof AuthenticatedProyectosIdRouteImport
      parentRoute: typeof AuthenticatedProyectosRoute
    }
  }
}

interface AuthenticatedProyectosRouteChildren {
  AuthenticatedProyectosIdRoute: typeof AuthenticatedProyectosIdRoute
}

const AuthenticatedProyectosRouteChildren: AuthenticatedProyectosRouteChildren =
  {
    AuthenticatedProyectosIdRoute: AuthenticatedProyectosIdRoute,
  }

const AuthenticatedProyectosRouteWithChildren =
  AuthenticatedProyectosRoute._addFileChildren(
    AuthenticatedProyectosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCobrosRoute: typeof AuthenticatedCobrosRoute
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGastosRoute: typeof AuthenticatedGastosRoute
  AuthenticatedGastosGeneralesRoute: typeof AuthenticatedGastosGeneralesRoute
  AuthenticatedProyectosRoute: typeof AuthenticatedProyectosRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCobrosRoute: AuthenticatedCobrosRoute,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGastosRoute: AuthenticatedGastosRoute,
  AuthenticatedGastosGeneralesRoute: AuthenticatedGastosGeneralesRoute,
  AuthenticatedProyectosRoute: AuthenticatedProyectosRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
